@startuml
skinparam backgroundColor #F9F9F9
skinparam shadowing true
skinparam class {
  ArrowColor #444444
  BorderColor #333333
}

!define table(x) class x << (T,#FFAAAA) >>

class User <<Entity>> {
  + id: UUID
  + name: str
  + email: str
  + password: str
  + created_at: datetime
  + updated_at: datetime
  --
  + signup(user: user_schema.UserCreate, db: Session): UserBase
  + login(user: auth_schema.LoginRequest, db: Session): LoginResponse
  + forget_password(data: auth_schema.ForgetPasswordRequest, db: Session): void
  + forget_password_confirm(data: auth_schema.ForgetPasswordConfirmRequest, db: Session): void
  + oauth_login(req: Request, provider: str): RedirectResponse
  + oauth_callback(request: Request, provider: str, db: Session): RedirectResponse
}


package "News (External API)" {
    class News <<Entity>> {
      + id: str
      + title: str
      + category_id: UUID
      --
      + news(): List[News]
      + detail(category:str, id:int): News
      + related_news(category: str, news_site: str): List[News]
      + news_by_category(category:str | int): List[News]
    }

    class Category <<Entity>> {
      + id: UUID
      + name: str
      --
      + get_all_categories(): List[Category]
    }
}

' Relaciones
Category ||--o{ News : "has"

@enduml
